spring:
  application:
    name: loltech-webchat-demo
  datasource:
    url: jdbc:h2:mem:webchat
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  h2:
    console:
      enabled: on
server:
  port: 8080
