create table message
(
    id          bigint generated by default as identity,
    sent_time   timestamp(6) not null,
    content     varchar(255) not null,
    sender_name varchar(255) not null,
    primary key (id)
);
